theme: jekyll-theme-cayman
title: Alberto's git sandbox
description: "A chaotic sandbox where half-baked brilliance and glorified experiments collide.  Bring curiosity, not expectations. Sometimes may contain traces of actual genius."